'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
0 1 2 3 5 8 13 21 34 55 89 .....
By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.

Input Format

First line contains  that denotes the number of test cases. This is followed by  lines, each containing an integer, .

Constraints

Output Format

Print the required answer for each test case.

Sample Input 0

2
10
100
Sample Output 0

10
44
Explanation 0

For N=10, we have {2,8}, sum is 10.
For N=100, we have {2,8,34}, sum is 44.
'''

import sys
n1=0
n2=1
count=0
lst=[]
t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    if(n<=0):
        lst=None
    elif(n==1):
        lst.append(n1)
    else:
        while(count<=n+n1):
            lst.append(n1)
            nth=n1+n2
            n1=n2
            n2=nth
            count=count+n1
        print(lst)
            #if(n1>=n):
            #    even_list = [ele for ele in lst if ele%2 ==0]
#print(lst)
#print(even_list)